"""hub updated

Revision ID: 1497c1deb76e
Revises: 6eda8a3e3906
Create Date: 2026-08-21 12:42:09.319898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1497c1deb76e'
down_revision = '6eda8a3e3906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
