"""updated contraints of zone and price rules

Revision ID: 149eedfee5a4
Revises: 45e0a1fcf8e1
Create Date: 2026-08-21 10:25:28.553124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149eedfee5a4'
down_revision = '45e0a1fcf8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pricing_rules_zone_id_fkey'), 'pricing_rules', type_='foreignkey')
    op.create_foreign_key(None, 'pricing_rules', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing_rules', type_='foreignkey')
    op.create_foreign_key(op.f('pricing_rules_zone_id_fkey'), 'pricing_rules', 'zones', ['zone_id'], ['id'])
    # ### end Alembic commands ###
