"""add cnic column

Revision ID: 24536c1d212e
Revises: ff5c44fa59e5
Create Date: 2026-07-07 03:26:35.791177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24536c1d212e'
down_revision = 'ff5c44fa59e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###
