"""add order messages and delivery attempt photo proof

Revision ID: 2c5ae81c9d71
Revises: 870c7656dbd1
Create Date: 2026-08-18 15:54:01.148634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5ae81c9d71'
down_revision = '870c7656dbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_messages_order_id'), 'order_messages', ['order_id'], unique=False)
    op.add_column('delivery_attempts', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_attempts', 'photo_url')
    op.drop_index(op.f('ix_order_messages_order_id'), table_name='order_messages')
    op.drop_table('order_messages')
    # ### end Alembic commands ###
