"""add marketplace products and ratings

Revision ID: 33492fe64bb8
Revises: 6c2cfe212634
Create Date: 2026-08-17 10:45:37.827176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33492fe64bb8'
down_revision = '6c2cfe212634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_weight_kg', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rater_role', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_business_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_phone', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_rating_score_range'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['target_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_order_id'), 'ratings', ['order_id'], unique=False)
    op.create_index(op.f('ix_ratings_target_business_id'), 'ratings', ['target_business_id'], unique=False)
    op.create_index(op.f('ix_ratings_target_phone'), 'ratings', ['target_phone'], unique=False)
    op.create_index(op.f('ix_ratings_target_user_id'), 'ratings', ['target_user_id'], unique=False)
    op.add_column('orders', sa.Column('product_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('unit_price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    # (pre-existing riders.cod_cash_held/cod_wallet_locked nullability drift
    # intentionally left alone here - unrelated to the marketplace feature)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'unit_price')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_id')
    op.drop_index(op.f('ix_ratings_target_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_target_phone'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_target_business_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_order_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
