"""add hubs and local offices

Revision ID: 424a30d88c7c
Revises: 2d7e6c1f8a3b
Create Date: 2026-08-20 12:20:09.239243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424a30d88c7c'
down_revision = '2d7e6c1f8a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('manager_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_offices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('manager_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('local_office_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'orders', 'local_offices', ['local_office_id'], ['id'])
    op.add_column('staff_profiles', sa.Column('hub_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('staff_profiles', sa.Column('local_office_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'staff_profiles', 'local_offices', ['local_office_id'], ['id'])
    op.create_foreign_key(None, 'staff_profiles', 'hubs', ['hub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_column('staff_profiles', 'local_office_id')
    op.drop_column('staff_profiles', 'hub_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'local_office_id')
    op.drop_table('local_offices')
    op.drop_table('hubs')
    # ### end Alembic commands ###
