"""branches on hub delete cascade

Revision ID: 42dea93975c5
Revises: e7f6a5b4c3d2
Create Date: 2026-08-21 09:59:48.140377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dea93975c5'
down_revision = 'e7f6a5b4c3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
