"""updated contraints

Revision ID: 45e0a1fcf8e1
Revises: 86f4946c6a67
Create Date: 2026-08-21 10:23:37.687492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e0a1fcf8e1'
down_revision = '86f4946c6a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hubs_manager_id_fkey'), 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('branches_zone_id_fkey'), 'hubs', type_='foreignkey')
    op.create_foreign_key(None, 'hubs', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('local_branches_branch_id_fkey'), 'local_branches', type_='foreignkey')
    op.create_foreign_key(None, 'local_branches', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('riders_hub_id_fkey'), 'riders', type_='foreignkey')
    op.create_foreign_key(None, 'riders', 'hubs', ['hub_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('staff_profiles_local_branch_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_hub_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_branch_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'local_branches', ['local_branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff_profiles', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff_profiles', 'hubs', ['hub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('staff_profiles_branch_id_fkey'), 'staff_profiles', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(op.f('staff_profiles_hub_id_fkey'), 'staff_profiles', 'hubs', ['hub_id'], ['id'])
    op.create_foreign_key(op.f('staff_profiles_local_branch_id_fkey'), 'staff_profiles', 'local_branches', ['local_branch_id'], ['id'])
    op.drop_constraint(None, 'riders', type_='foreignkey')
    op.create_foreign_key(op.f('riders_hub_id_fkey'), 'riders', 'hubs', ['hub_id'], ['id'])
    op.drop_constraint(None, 'local_branches', type_='foreignkey')
    op.create_foreign_key(op.f('local_branches_branch_id_fkey'), 'local_branches', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(None, 'hubs', type_='foreignkey')
    op.create_foreign_key(op.f('branches_zone_id_fkey'), 'hubs', 'zones', ['zone_id'], ['id'])
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key(op.f('hubs_manager_id_fkey'), 'branches', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###
