"""announcement back populated hub

Revision ID: 4769e6d4738e
Revises: 258d9c734342
Create Date: 2026-08-21 11:58:18.325126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4769e6d4738e'
down_revision = '258d9c734342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
