"""add rider status requests, parcel unlock requests, support tickets

Revision ID: 47eb7b5feedb
Revises: f4a9b3e8c217
Create Date: 2026-08-18 10:14:23.305317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47eb7b5feedb'
down_revision = 'f4a9b3e8c217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_status_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rider_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_is_available', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus', native_enum=False, length=20), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rider_status_requests_rider_id'), 'rider_status_requests', ['rider_id'], unique=False)
    op.create_index(op.f('ix_rider_status_requests_status'), 'rider_status_requests', ['status'], unique=False)
    op.create_table('parcel_unlock_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rider_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus', native_enum=False, length=20), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_unlock_requests_order_id'), 'parcel_unlock_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_parcel_unlock_requests_rider_id'), 'parcel_unlock_requests', ['rider_id'], unique=False)
    op.create_index(op.f('ix_parcel_unlock_requests_status'), 'parcel_unlock_requests', ['status'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('raised_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='supportticketstatus', native_enum=False, length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_raised_by_id'), 'support_tickets', ['raised_by_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_table('support_ticket_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticket_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_ticket_messages_ticket_id'), 'support_ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_ticket_messages_ticket_id'), table_name='support_ticket_messages')
    op.drop_table('support_ticket_messages')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_raised_by_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_parcel_unlock_requests_status'), table_name='parcel_unlock_requests')
    op.drop_index(op.f('ix_parcel_unlock_requests_rider_id'), table_name='parcel_unlock_requests')
    op.drop_index(op.f('ix_parcel_unlock_requests_order_id'), table_name='parcel_unlock_requests')
    op.drop_table('parcel_unlock_requests')
    op.drop_index(op.f('ix_rider_status_requests_status'), table_name='rider_status_requests')
    op.drop_index(op.f('ix_rider_status_requests_rider_id'), table_name='rider_status_requests')
    op.drop_table('rider_status_requests')
    # ### end Alembic commands ###
