"""updated  invoice order constraint

Revision ID: 57cbb99dc9a5
Revises: 8f44bdcc782f
Create Date: 2026-08-21 10:40:42.027683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cbb99dc9a5'
down_revision = '8f44bdcc782f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_order_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_order_id_fkey'), 'invoices', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
