"""announcement and hub relationship constraint updated

Revision ID: 5932aa226f3a
Revises: 7fe5032c218d
Create Date: 2026-08-21 12:29:05.676332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5932aa226f3a'
down_revision = '7fe5032c218d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
