"""warehouses on hub delete cascade

Revision ID: 6a849a07bda2
Revises: bb1f33b164f2
Create Date: 2026-08-21 10:10:27.095103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a849a07bda2'
down_revision = 'bb1f33b164f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('warehouses_hub_id_fkey'), 'warehouses', type_='foreignkey')
    op.create_foreign_key(None, 'warehouses', 'hubs', ['hub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_foreign_key(op.f('warehouses_hub_id_fkey'), 'warehouses', 'hubs', ['hub_id'], ['id'])
    # ### end Alembic commands ###
