"""state machine v2, rider cod wallet, disputes

Revision ID: 6c2cfe212634
Revises: c8de8cbce935
Create Date: 2026-08-13 13:34:58.780197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c2cfe212634'
down_revision = 'c8de8cbce935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('raised_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'rejected', name='disputestatus', native_enum=False, length=20), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('created', 'assigned', 'picked_up', 'in_transit', 'delivered', 'failed', 'cancelled', name='orderstatus'),
               type_=sa.String(length=30),
               existing_nullable=True,
               postgresql_using='status::text')
    op.add_column('riders', sa.Column('cod_cash_held', sa.Float(), nullable=False, server_default='0'))
    op.add_column('riders', sa.Column('cod_wallet_locked', sa.Boolean(), nullable=False, server_default=sa.false()))
    # The old native Postgres enum type is now unused (column is varchar) - drop it so it
    # doesn't linger as dead schema.
    op.execute('DROP TYPE IF EXISTS orderstatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'cod_wallet_locked')
    op.drop_column('riders', 'cod_cash_held')
    orderstatus_enum = postgresql.ENUM('created', 'assigned', 'picked_up', 'in_transit', 'delivered', 'failed', 'cancelled', name='orderstatus')
    orderstatus_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=30),
               type_=orderstatus_enum,
               existing_nullable=True,
               postgresql_using='status::orderstatus')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
