"""Initial table generation

Revision ID: 6d983354070d
Revises: f0b9ba189793
Create Date: 2026-08-13 11:06:56.472570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d983354070d'
down_revision = 'f0b9ba189793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
