"""announcements hub fk cascade

Revision ID: 6eda8a3e3906
Revises: 5932aa226f3a
Create Date: 2026-08-21 12:39:16.895568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eda8a3e3906'
down_revision = '5932aa226f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('announcements_hub_id_fkey'), 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'hubs', ['hub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key(op.f('announcements_hub_id_fkey'), 'announcements', 'hubs', ['hub_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
