"""initial tables

Revision ID: 7c66bd1df27f
Revises: f301924cfc53
Create Date: 2026-07-06 12:20:35.270694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c66bd1df27f'
down_revision = 'f301924cfc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
