"""refresh_schema_change

Revision ID: 7efe48130e6c
Revises: 7c66bd1df27f
Create Date: 2026-07-07 03:16:48.760791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efe48130e6c'
down_revision = '7c66bd1df27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.String(length=15), nullable=False))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###
