"""announcement and hub relationship constraint updated

Revision ID: 7fe5032c218d
Revises: 4769e6d4738e
Create Date: 2026-08-21 12:27:53.277515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe5032c218d'
down_revision = '4769e6d4738e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
