"""updated all order contrints

Revision ID: 847605afc904
Revises: 57cbb99dc9a5
Create Date: 2026-08-21 10:47:14.292366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847605afc904'
down_revision = '57cbb99dc9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('disputes_order_id_fkey'), 'disputes', type_='foreignkey')
    op.create_foreign_key(None, 'disputes', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('manifest_items_order_id_fkey'), 'manifest_items', type_='foreignkey')
    op.create_foreign_key(None, 'manifest_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_notifications_order_id_orders'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_messages_order_id_fkey'), 'order_messages', type_='foreignkey')
    op.create_foreign_key(None, 'order_messages', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('parcel_incidents_order_id_fkey'), 'parcel_incidents', type_='foreignkey')
    op.create_foreign_key(None, 'parcel_incidents', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('parcel_unlock_requests_order_id_fkey'), 'parcel_unlock_requests', type_='foreignkey')
    op.create_foreign_key(None, 'parcel_unlock_requests', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ratings_order_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('settlements_order_id_fkey'), 'settlements', type_='foreignkey')
    op.create_foreign_key(None, 'settlements', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('support_tickets_order_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tracking_events_order_id_fkey'), 'tracking_events', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_events', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_events', type_='foreignkey')
    op.create_foreign_key(op.f('tracking_events_order_id_fkey'), 'tracking_events', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_order_id_fkey'), 'support_tickets', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.create_foreign_key(op.f('settlements_order_id_fkey'), 'settlements', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_order_id_fkey'), 'ratings', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'parcel_unlock_requests', type_='foreignkey')
    op.create_foreign_key(op.f('parcel_unlock_requests_order_id_fkey'), 'parcel_unlock_requests', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'parcel_incidents', type_='foreignkey')
    op.create_foreign_key(op.f('parcel_incidents_order_id_fkey'), 'parcel_incidents', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_messages', type_='foreignkey')
    op.create_foreign_key(op.f('order_messages_order_id_fkey'), 'order_messages', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notifications_order_id_orders'), 'notifications', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'manifest_items', type_='foreignkey')
    op.create_foreign_key(op.f('manifest_items_order_id_fkey'), 'manifest_items', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.create_foreign_key(op.f('disputes_order_id_fkey'), 'disputes', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
