"""warehouses on hub delete cascade added

Revision ID: 86f4946c6a67
Revises: 6a849a07bda2
Create Date: 2026-08-21 10:11:59.304750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f4946c6a67'
down_revision = '6a849a07bda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
