"""add staff attendance and branch service areas

Revision ID: 870c7656dbd1
Revises: c5d8e9f0a321
Create Date: 2026-08-18 15:20:47.785386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870c7656dbd1'
down_revision = 'c5d8e9f0a321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_service_areas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('zone_name', sa.String(length=150), nullable=False),
    sa.Column('postal_codes', sa.String(length=100), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('same_day', sa.Boolean(), nullable=True),
    sa.Column('express', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_service_areas_branch_id'), 'branch_service_areas', ['branch_id'], unique=False)
    op.add_column('staff_profiles', sa.Column('attendance_status', sa.String(length=20), nullable=False, server_default='present'))
    op.alter_column('staff_profiles', 'attendance_status', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_profiles', 'attendance_status')
    op.drop_index(op.f('ix_branch_service_areas_branch_id'), table_name='branch_service_areas')
    op.drop_table('branch_service_areas')
    # ### end Alembic commands ###
