"""updated order foreign key containts

Revision ID: 886ecd3aba00
Revises: 149eedfee5a4
Create Date: 2026-08-21 10:29:35.267444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886ecd3aba00'
down_revision = '149eedfee5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_hub_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_zone_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'hubs', ['hub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_zone_id_fkey'), 'orders', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(op.f('orders_hub_id_fkey'), 'orders', 'hubs', ['hub_id'], ['id'])
    # ### end Alembic commands ###
