"""updated bus network updated

Revision ID: 8cb461d3af44
Revises: 886ecd3aba00
Create Date: 2026-08-21 10:32:07.600633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb461d3af44'
down_revision = '886ecd3aba00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bus_schedules_destination_hub_id_fkey'), 'bus_schedules', type_='foreignkey')
    op.drop_constraint(op.f('bus_schedules_origin_hub_id_fkey'), 'bus_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'bus_schedules', 'hubs', ['origin_hub_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bus_schedules', 'hubs', ['destination_hub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bus_schedules', type_='foreignkey')
    op.drop_constraint(None, 'bus_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('bus_schedules_origin_hub_id_fkey'), 'bus_schedules', 'hubs', ['origin_hub_id'], ['id'])
    op.create_foreign_key(op.f('bus_schedules_destination_hub_id_fkey'), 'bus_schedules', 'hubs', ['destination_hub_id'], ['id'])
    # ### end Alembic commands ###
