"""updated delivery attempt order constraint

Revision ID: 8f44bdcc782f
Revises: 8cb461d3af44
Create Date: 2026-08-21 10:38:03.023978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f44bdcc782f'
down_revision = '8cb461d3af44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('delivery_attempts_order_id_fkey'), 'delivery_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_attempts', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_attempts_order_id_fkey'), 'delivery_attempts', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
