"""initial tables

Revision ID: 9068b9cd6113
Revises: 9987f98db618
Create Date: 2026-07-07 07:45:29.746514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9068b9cd6113'
down_revision = '9987f98db618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
