"""new updated tables

Revision ID: 9987f98db618
Revises: 6a50eaf2d3a6
Create Date: 2026-07-07 07:33:10.820954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9987f98db618'
down_revision = '6a50eaf2d3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
