"""updated all bus schedule constraint

Revision ID: 9bf9be2d6082
Revises: 847605afc904
Create Date: 2026-08-21 10:54:31.847004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf9be2d6082'
down_revision = '847605afc904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bus_manifests_schedule_id_fkey'), 'bus_manifests', type_='foreignkey')
    op.create_foreign_key(None, 'bus_manifests', 'bus_schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bus_manifests', type_='foreignkey')
    op.create_foreign_key(op.f('bus_manifests_schedule_id_fkey'), 'bus_manifests', 'bus_schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
