"""initial tables

Revision ID: 9e637ac9b984
Revises: a7b28402abfb
Create Date: 2026-07-07 07:58:03.096303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e637ac9b984'
down_revision = 'a7b28402abfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
