"""initial tables

Revision ID: a10b0a50f512
Revises: dfce4494bea0
Create Date: 2026-07-05 15:50:29.008453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10b0a50f512'
down_revision = 'dfce4494bea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
