"""initial tables

Revision ID: a7b28402abfb
Revises: 9068b9cd6113
Create Date: 2026-07-07 07:50:03.874451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b28402abfb'
down_revision = '9068b9cd6113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
