"""branches on hub delete cascade added

Revision ID: bb1f33b164f2
Revises: 42dea93975c5
Create Date: 2026-08-21 10:04:40.900606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1f33b164f2'
down_revision = '42dea93975c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branches_hub_id_fkey'), 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'hubs', ['hub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key(op.f('branches_hub_id_fkey'), 'branches', 'hubs', ['hub_id'], ['id'])
    # ### end Alembic commands ###
