"""add zone and branch associations

Revision ID: bbc7a0a5a593
Revises: 7b415a1837c0
Create Date: 2026-07-07 09:36:17.094128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc7a0a5a593'
down_revision = '7b415a1837c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('zone_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'branches', 'zones', ['zone_id'], ['id'])
    op.add_column('orders', sa.Column('zone_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('orders', sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'orders', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'zones', ['zone_id'], ['id'])
    op.add_column('rider_profiles', sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'rider_profiles', 'branches', ['branch_id'], ['id'])
    op.add_column('staff_profiles', sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'staff_profiles', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_column('staff_profiles', 'branch_id')
    op.drop_constraint(None, 'rider_profiles', type_='foreignkey')
    op.drop_column('rider_profiles', 'branch_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'branch_id')
    op.drop_column('orders', 'zone_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'zone_id')
    # ### end Alembic commands ###
