"""add cod settlement, bus network, rnp, wallet, seller upload, discount

Revision ID: c8de8cbce935
Revises: 6d983354070d
Create Date: 2026-08-13 11:36:32.253848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8de8cbce935'
down_revision = '6d983354070d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_operators',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.Enum('percentage', 'flat', name='discounttype'), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('max_discount_amount', sa.Float(), nullable=True),
    sa.Column('min_order_value', sa.Float(), nullable=True),
    sa.Column('requires_login', sa.Boolean(), nullable=True),
    sa.Column('is_auto_applied', sa.Boolean(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=True)
    op.create_table('reconciliation_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('reconciled_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rnp_partners',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('shop_name', sa.String(length=150), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'suspended', name='rnppartnerstatus'), nullable=True),
    sa.Column('approved_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rnp_partners_status'), 'rnp_partners', ['status'], unique=False)
    op.create_table('seller_uploads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('transaction_type', sa.Enum('settlement_credit', 'cod_debit', 'adjustment', 'fee', name='wallettransactiontype'), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operator_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('origin_branch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('destination_branch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('departure_time', sa.String(length=10), nullable=True),
    sa.Column('departure_interval_min', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['bus_operators.id'], ),
    sa.ForeignKeyConstraint(['origin_branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_manifests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schedule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('manifest_number', sa.String(length=50), nullable=True),
    sa.Column('coach_number', sa.String(length=50), nullable=True),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_city', sa.String(length=100), nullable=True),
    sa.Column('destination_city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('in_preparation', 'in_transit', 'arrived', name='manifeststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['bus_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_manifests_manifest_number'), 'bus_manifests', ['manifest_number'], unique=True)
    op.create_index(op.f('ix_bus_manifests_status'), 'bus_manifests', ['status'], unique=False)
    op.create_table('manifest_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('manifest_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('crate_label', sa.String(length=100), nullable=True),
    sa.Column('scan_status', sa.Enum('loaded', 'in_transit', 'arrived', 'delivered', name='scanstatus'), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['bus_manifests.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_items_scan_status'), 'manifest_items', ['scan_status'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('payment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('settle_due_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', name='settlementstatus'), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['settled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.add_column('businesses', sa.Column('wallet_locked', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('wallet_lock_reason', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('discount_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'discounts', ['discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'discount_id')
    op.drop_column('businesses', 'wallet_lock_reason')
    op.drop_column('businesses', 'wallet_locked')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_manifest_items_scan_status'), table_name='manifest_items')
    op.drop_table('manifest_items')
    op.drop_index(op.f('ix_bus_manifests_status'), table_name='bus_manifests')
    op.drop_index(op.f('ix_bus_manifests_manifest_number'), table_name='bus_manifests')
    op.drop_table('bus_manifests')
    op.drop_table('bus_schedules')
    op.drop_table('wallet_transactions')
    op.drop_table('seller_uploads')
    op.drop_index(op.f('ix_rnp_partners_status'), table_name='rnp_partners')
    op.drop_table('rnp_partners')
    op.drop_table('reconciliation_logs')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_table('bus_operators')
    # ### end Alembic commands ###
