"""payout method + receipt on settlements, dispute evidence

Revision ID: d1f5a3b2c490
Revises: 49416eb623aa
Create Date: 2026-08-17 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd1f5a3b2c490'
down_revision = '49416eb623aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('payout_method', sa.String(length=50), nullable=True))
    op.add_column('settlements', sa.Column('receipt_url', sa.String(length=300), nullable=True))
    op.add_column('disputes', sa.Column('evidence_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'evidence_urls')
    op.drop_column('settlements', 'receipt_url')
    op.drop_column('settlements', 'payout_method')
    # ### end Alembic commands ###