"""initial tables

Revision ID: dfce4494bea0
Revises: 3f01396a0d13
Create Date: 2026-07-05 15:41:23.094645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfce4494bea0'
down_revision = '3f01396a0d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
