"""per-rider cod wallet limits

Revision ID: e2b6c4d5a601
Revises: d1f5a3b2c490
Create Date: 2026-08-17 15:20:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e2b6c4d5a601'
down_revision = 'd1f5a3b2c490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('cod_wallet_limit', sa.Float(), nullable=False, server_default='30000'))
    op.add_column('riders', sa.Column('cod_wallet_warning_at', sa.Float(), nullable=False, server_default='25000'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'cod_wallet_warning_at')
    op.drop_column('riders', 'cod_wallet_limit')
    # ### end Alembic commands ###