"""initial tables

Revision ID: f301924cfc53
Revises: a10b0a50f512
Create Date: 2026-07-06 10:32:22.007537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f301924cfc53'
down_revision = 'a10b0a50f512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rider_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'rider_accepted')
    # ### end Alembic commands ###
