"""corridor pricing and active flag

Revision ID: f4a9b3e8c217
Revises: e2b6c4d5a601
Create Date: 2026-08-17 16:05:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4a9b3e8c217'
down_revision = 'e2b6c4d5a601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('base_rate', sa.Float(), nullable=False, server_default='5.0'))
    op.add_column('zones', sa.Column('cod_fee_percentage', sa.Float(), nullable=False, server_default='3.0'))
    op.add_column('routes', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'is_active')
    op.drop_column('zones', 'cod_fee_percentage')
    op.drop_column('zones', 'base_rate')
    # ### end Alembic commands ###