"""add cnic column

Revision ID: ff5c44fa59e5
Revises: 7efe48130e6c
Create Date: 2026-07-07 03:23:50.141383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5c44fa59e5'
down_revision = '7efe48130e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.String(length=15), nullable=False))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###
